config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :articles
    resources :anals do
      collection do
        get 'remove_all'
      end
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
end

app/models/anal.rb
class Anal < ApplicationRecord
  belongs_to :user
  validates :name, presence: true

  before_save do
    anals = Anal.where(name: self.name)
    self.count += anals.count if anals.count >= 1
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  has_many :anals
end

app/controllers/anals_controller.rb
class AnalsController < ApplicationController
  before_action :set_anal, only: %i[ show edit update destroy ]

  # GET /anals or /anals.json
  def index
    @anals = Anal.where(user_id: params[:user_id]).order('count DESC')
    @uniqAnals = @anals.uniq { |anal| anal.name }
  end

  # GET /anals/1 or /anals/1.json
  def show
  end

  # GET /anals/new
  def new
    @anal = Anal.new
  end

  # GET /anals/1/edit
  def edit
  end

  # POST /anals or /anals.json
  def create
    @anal = Anal.new(anal_params)
    @anal.user_id = params[:user_id]

    respond_to do |format|
      if @anal.save
        format.json { render json: @anal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @anal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /anals/1 or /anals/1.json
  def update
    respond_to do |format|
      if @anal.update(anal_params)
        format.json { render json: @anal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @anal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /anals/1 or /anals/1.json
  def destroy
    Anal.where(user_id: params[:user_id]).order('count DESC').destroy_all
    redirect_to "/users/#{params[:user_id]}/articles"
    # respond_to do |format|
    #   format.html { redirect_to user_articles_path(params[:user_id]), notice: "Anal was successfully destroyed." }
    #   format.json { head :no_content }
    # end
  end

  def remove_all
    Anal.where(user_id: params[:user_id]).order('count DESC').delete_all
    flash[:notice] = "You have removed all results!"
    redirect_to user_articles_path(params[:user_id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_anal
      @anal = Anal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def anal_params
      params.permit(:name, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.where(user_id: params[:user_id])
  end

  # GET /articles/1 or /articles/1.json
  def show
    @k = User.find(params[:user_id])
  end

  # GET /articles/new
  def new
    @article = Article.new
    @articles = Article.all
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    @article.user_id = params[:user_id]

    respond_to do |format|
      if @article.save
        format.html { redirect_to user_article_url(params[:user_id],@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.permit(:name, :paragraph, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
    redirect_to '/users/1/articles'
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/anals_helper.rb
module AnalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/anals/_anal.html.erb
<div id="<%= dom_id anal %>">
  <p>🕓 <%= anal.name %> (<%= anal.count%>)</p>

</div>

app/views/anals/edit.html.erb
<h1>Editing anal</h1>

<%= render "form", anal: @anal %>

<br>

<div>
  <%= link_to "Show this anal", @anal %> |
  <%= link_to "Back to anals", anals_path %>
</div>

app/views/anals/index.html.erb
<%= link_to "Back", user_articles_path(params[:user_id]) %>

<h1>Search Analytics</h1>

<div id="anals">
  <% if @uniqAnals.any? %>
    <% @uniqAnals.each do |anal| %>
      <%= render anal %>
    <% end %>
  <% else %>
    <h3>Nothing searched yet😥</h3>
  <% end %>
  <%= link_to "Clear All", remove_all_user_anals_path(params[:user_id]), :method => :get %>
</div>

app/views/anals/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @anal %>

<div>
  <%= link_to "Edit this anal", edit_anal_path(@anal) %> |
  <%= link_to "Back to anals", anals_path %>

  <%= button_to "Destroy this anal", @anal, method: :delete %>
</div>

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>" class="article">
  <p><%= article.name %></p>

  <p><%= article.paragraph %></p>

</div>

app/views/articles/_form.html.erb
<%= form_with url: user_articles_path(params[:user_id]) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :paragraph, style: "display: block" %>
    <%= form.text_field :paragraph %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<nav>

  <% if params[:user_id] == "1" %>  
  
    <%= link_to "Search analytics", "/users/1/anals" %> 
  
  <% else %> 
  
     <%= link_to "Search analytics", "/users/2/anals" %> 
  
  <% end %> 
  
  <div class="profile-pic <%= "color-change" if params[:user_id] == "2" %>"><%= User.find(params[:user_id]).name[0] %></div>

</nav>

<dialog class="modal">
<div class="modal-first-container">
  <span>Users</span>
  <button name="close-btn" type="button">X</button>
</div>
  <% User.all.each do |i| %>
    <div>
      <div class="profile-pic <%= "color-change" if i.id == 2 %>"><%= i.name[0] %></div>
      <%= link_to i.name, user_articles_path(i.id) %>
    </div>
  <% end %>
</dialog>

<form accept-charset="UTF-8" class="search-form">
  <p>🔍</p>
  <input id="search" placeholder="Search articles" />
</form>

<h1>Articles</h1>

<div id="articles">
  <% @articles.each do |article| %>
    <%= render article %>
  <% end %>
</div>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", user_articles_path %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_user_article_path(params[:user_id], @article) %> |
  <%= link_to "Back to articles", user_articles_path(params[:user_id]) %>

  <%= button_to "Destroy this article", user_article_path(@k, params[:id]), method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Analytics</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user  %>
    <p>
      <%= link_to "Show this user's articles", "/users/#{user.id}/articles" %>
    </p>
  <% end %>
</div>

<%# <%= link_to "See search analytics", "/users/#{@user.id}/anals" %> 

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<div >
<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>
</div>